.\"     Title: apt-mark-sync
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 01/02/2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "APT\-MARK\-SYNC" "1" "01/02/2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
apt-mark-sync - synchronize the 'automatically installed' field between package managers
.SH "SYNOPSIS"
\fBapt\-mark\-sync\fR \fIREADER\fR [all | \fIWRITER\fR \&...]
.sp
.SH "DESCRIPTION"
Currently \fBapt\fR, \fBaptitude\fR, \fBdebfoster\fR and \fBdeborphan\fR each keep their own status database of which packages have been installed manually (i\.e\. the user requested their installation) and which have been installed automatically (i\.e\. they were installed as dependencies of manually installed packages)\.
.sp
apt\-mark\-sync reads the status for each package from one of the databases and writes it to the others\. For instance, if you set a package as manually installed in debfoster and run \fBapt\-mark\-sync debfoster apt aptitude\fR, both apt and aptitude consider it to be manually installed\.
.sp
Note that it\'s not recommended to use apt as a sync source, since it\'s much easier to manage the packages\' auto\-installed status with debfoster, deborphan or aptitude\.
.sp
.SH "EXAMPLES"
.PP
\fBaptitude install debfoster; apt\-mark\-sync aptitude all\fR
.RS 4
Synchronizes from aptitude to apt, debfoster and deborphan\.
.RE
.PP
\fBdebfoster; apt\-mark\-sync debfoster all\fR
.RS 4
Synchronizes from debfoster to apt, aptitude and deborphan\.
.RE
.SH "AUTHOR"
Written by Johan Kiviniemi <\fIdebian@johan\.kiviniemi\.name\fR\&[1]>
.sp
.SH "RESOURCES"
Web site: \fIhttp://johan\.kiviniemi\.name/software/apt\-mark\-sync/\fR
.sp
Git branch: git://heh\.fi/ion/apt\-mark\-sync\.git
.sp
Git browser: \fIhttp://gitweb\.heh\.fi/?p=ion/apt\-mark\-sync\.git\fR
.sp
.SH "SEE ALSO"
\fBams\-run\fR(1)
.sp
.SH "COPYRIGHT"
Copyright \(co 2008 Johan Kiviniemi
.sp
This is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version\. There is NO WARRANTY, to the extent permitted by law\.
.sp
.SH "NOTES"
.IP " 1." 4
debian@johan.kiviniemi.name
.RS 4
\%mailto:debian@johan.kiviniemi.name
.RE
